### ISSUE TITLE
jump to file with sybolic link in path opens new tab instead of focussing an existing one

### ISSUE THREAD

**Issue by drevicko** [jonathandelgado/SublimeTodoReview#107] opened 2015-04-01 04:44 UTC
(on Ubuntu 12.04, slublimetext build 3083, TodoReview up to date according to package control)

When a file resides in a subfolder of a symbolically linked folder, TodoReview opens a new tab with the files physical path instead of moving focus to the already existent tab with the files symbolic path.

SublimeText (perhaps understandably) recognises them as two different files. This is a problem when you inadvertently edit both!

**Comment by jonathandelgado** [comment] 2015-04-01 15:36
Alright, I took a look into this and i've confirmed the issue. However, there isn't anything I can do about it. Sublime unfortunately passes the physical path to the plugin, so TodoReview is unable to distinguish the difference.

If you have any ideas, I would be more than happy to entertain them.

**Comment by drevicko** [comment] 2015-04-02 05:22
Perhaps we should log an issue with sublime? 
What's the api call that returns the path?

**Comment by jonathandelgado** [comment] 2015-04-02 14:24
`active_window().folders()`, try using your sublime console (`ctrl + ~`) to confirm that is the issue.

**Comment by drevicko** [comment] 2015-04-03 01:16
ok, I tried it on osx (the command I used was `sublime.active_window().active_view().file_name()`, `sublime.active_window().folders()` is giving me an empty list). 

Anyway, in the osx version, if you open a file in a symlinked directory, it opens the file with the physical file path, so the problem doesn't appear to be happening. I wasn't able to get two copies of the file open.

I'll try with my Ubuntu box in the office when I get the chance.

**Comment by jonathandelgado** [comment] 2015-04-05 04:07
Keep me informed.

**Comment by drevicko** [comment] 2015-04-05 09:33
I submitted a bug with sublime: https://github.com/SublimeTextIssues/Core/issues/778

**Comment by jonathandelgado** [comment] 2015-04-05 16:01
Oh ok, I'll just close this then, let me know if there is anything else I can do.

**Closed by jonathandelgado** 2015-04-05 16:01 UTC

**Comment by drevicko** [comment] 2018-02-27 17:20
I've hit this problem again, this time when a file is opened via the `rsub` plugin from a remote host. The tab rsub opens has a symlinked path (it's in `/var/` which on current osx is a symlink to `/private/var/`). This symlinked path is returned by `sublime.active_window().folders()`.

When I run TodoReview and use a link in the TODO list tab, the file is opened in a new tab with the physical path, and it is this physical path returned by `sublime.active_window().folders()` as well as the right-click menu (which I presume uses the same function).

fwiw `sublime.active_window().folders()` is still giving me an empty list.

**Comment by jonathandelgado** [comment] 2018-02-27 22:23
Yeah, unfortunately I don't think I would be able to support that use-case since the `rsub` plugin has to do a few hacks to get the filesystem to appear as it does. I'm basically limited as a plugin developer to the sublime API.

**Comment by drevicko** [comment] 2018-02-28 10:17
ok. I think it shouldn't be a problem. It almost looks like sublimetext is reporting an absolute path in one context (eg: when the command is first run/instantiated) and the path that was opened, which may include a symbolic link, in another context (eg: when the Engine class is finding the list of open files). Both times, the same sublime API command is being used, so they should come up the same irrespective of whether it's a symlink path etc.. 

I'm looking into it...

**Comment by drevicko** [comment] 2018-02-28 10:58
ok, the problem is [here](https://github.com/jonathandelgado/SublimeTodoReview/blob/f85459c350722fe250536b8da61ca2bc29e981d8/TodoReview.py#L116)

Currently `os.path.realpath` is used on all file names. This returns the physical path of the file without symlinks. If I remove `os.path.realpath`, things work as expected.

Can you think of any particular reasons why `realpah` is used? (it's not a typo on `relpath` which returns a path relative to the cwd?)
